---
title: "Are carbon dioxide concentrations and global surface temperatures correlated?"
author: "Nomdeploom"
date: "October 31, 2018"
draft: false
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Measures of correlation and procedures for exploring correlation

A measure of correlation is a numerical measure of the relationship between 2 variables (X and Y), where the measurements are taken in pairs - one measurement for each variable. By convention, such measures are crafted so that they meet the following requirements:
 

* They lie between $-1$ and $1$;
* If larger values of X tend to group with larger values of Y and vice versa, the measure will be positive. If larger values of X tend to group with smaller values of Y and vice versa, the measure will be negative;
* The stronger the tendency to group large with large and small with small, the closer the measure will be to $1$; and 
* The stronger the tendency to group large with small, the closer the measure will be to $-1$.

Our process will consist of two phases: First, we will perform an exploratory review of the data to see if possible correlation surfaces. Second, we will calculate various the various correlation measures and see if they indicate correlation.


### Exploratory review of the time series and their relationship

